url: https://Gauri-Tripathi.github.io
baseurl: ''
lang: en
title: Gauri Tripathi
description: test
tagline: Currently seeking an opportunity in the Machine Learning and Data Science industry.

author:
  name: Gauri Tripathi
  email: gauritr19@gmail.com
  social:
    twitter: https://x.com/Gauri_the_great
    github: https://github.com/GauriTr
    linkedin: https://www.linkedin.com/in/gauri-tripathi-153078254

menu:
  - title: Projects
    url: /projects/
  - title: Resume
    url: /about/

copyright: Gauri Tripathi

# Basic Jekyll settings
permalink: /:categories/:year-:month-:day-:title/
paginate: 10
paginate_path: /page-:num/

# Theme customization
accent_color: rgb(79,177,186)
theme_color: rgb(25,55,71)
font: Noto Sans, Helvetica, Arial, sans-serif
font_heading: Roboto Slab, Helvetica, Arial, sans-serif

# Collections
collections:
  projects:
    permalink: /projects/:path/
    output: true

# Essential plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Basic compression
compress_html:
  clippings: all
  endings: all

sass:
  style: compressed
